/**
 * Base API Configuration for RTK Query
 *
 * Enterprise Best Practices:
 * - Single API slice per base URL (RTK Query recommendation)
 * - Centralized error handling with retry logic
 * - Tag-based cache invalidation system
 * - TypeScript type safety throughout
 * - Axios integration for consistent HTTP behavior
 * - Toast notifications via custom middleware
 *
 * MNC Standards:
 * - Scalable architecture for large codebases
 * - Code splitting support for lazy-loaded endpoints
 * - Standardized error responses
 * - Request/response transformations
 * - Authentication token management
 */

import { createApi } from '@reduxjs/toolkit/query/react';
import { axiosBaseQuery } from './axiosBaseQuery';

/**
 * Tag Types for Cache Invalidation
 *
 * Best Practice: Centralize all tag types in one place
 * This allows easy management of cache dependencies across the application
 */
export const TAG_TYPES = {
  USERS: 'Users',
  USER: 'User',
  POSTS: 'Posts',
  POST: 'Post',
  COMMENTS: 'Comments',
  TODOS: 'Todos',
  // Add more resource types as needed
} as const;

export type TagType = (typeof TAG_TYPES)[keyof typeof TAG_TYPES];

/**
 * Base API Slice
 *
 * This is the foundation API slice that all endpoints will be injected into.
 * Using code splitting pattern for better organization in large applications.
 */
export const baseApi = createApi({
  /**
   * Unique key for mounting the API slice in the Redux store
   */
  reducerPath: 'api',

  /**
   * Base query function using Axios
   * This allows us to leverage existing Axios interceptors and configuration
   */
  baseQuery: axiosBaseQuery({
    baseUrl: 'https://jsonplaceholder.typicode.com',
  }),

  /**
   * Tag types used for cache invalidation
   * Define all possible tags upfront for better TypeScript support
   */
  tagTypes: Object.values(TAG_TYPES),

  /**
   * Endpoints are defined separately and injected via code splitting
   * This keeps the base API clean and allows for better organization
   *
   * Empty object here - endpoints will be injected in separate files
   */
  endpoints: () => ({}),

  /**
   * Keep unused data in cache for 60 seconds by default
   * Can be overridden per endpoint
   */
  keepUnusedDataFor: 60,

  /**
   * Refetch on mount or arg change by default
   * This ensures fresh data when components mount
   */
  refetchOnMountOrArgChange: 30, // 30 seconds

  /**
   * Refetch on reconnect to ensure fresh data after network recovery
   */
  refetchOnReconnect: true,

  /**
   * Don't refetch on window focus by default (can be enabled per endpoint)
   * This prevents unnecessary API calls when switching browser tabs
   */
  refetchOnFocus: false,
});

/**
 * Export hooks for usage in components
 * These are auto-generated by RTK Query based on endpoint definitions
 */
export const {
  // Hooks will be auto-generated when endpoints are injected
  // e.g., useGetUsersQuery, useCreateUserMutation, etc.
} = baseApi;

/**
 * Export for store configuration
 */
export default baseApi;
